In [2]:
import pandas as pd
agg_vig = pd.read_csv(r"C:\Users\luktu\Downloads\gawll (1)\others\eVIG_dataset_pavia_c1_a1_r1.csv", header=None).values

In [3]:
agg_vig.shape

(103, 103)

In [11]:
cluster_centers_indices

array([ 1,  3, 10, 16, 22, 28, 32, 39, 47, 50, 54, 63, 64, 66, 67, 68, 84,
       86, 87, 90, 93, 98], dtype=int64)

In [12]:
labels

array([18,  0,  4,  1, 11, 16,  8,  6,  6,  2,  2, 20, 11,  8,  2,  1,  3,
       17, 18, 14,  3, 13,  4,  0, 13,  6,  0,  5,  5, 10,  4,  9,  6, 19,
        1, 11, 14, 14,  7,  7, 19,  2, 21, 18,  4, 18, 10,  8,  8, 21,  9,
       18, 11, 15, 10,  3, 13,  1, 16,  6,  9, 10,  6, 11, 12,  3, 13, 14,
       15, 21,  1,  0, 15, 11,  9, 17,  8,  6, 17, 14, 20, 14,  3,  4, 16,
        5, 17, 18,  9,  2, 19, 15,  1, 20, 14, 17,  2, 12, 21, 19, 12, 13,
       12], dtype=int64)

In [13]:
import numpy as np
np.unique(labels, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21], dtype=int64),
 array([4, 6, 6, 5, 5, 3, 7, 2, 5, 5, 4, 6, 4, 5, 7, 4, 3, 5, 6, 4, 3, 4],
       dtype=int64))